<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-29 at 17:44:00.
 */
class compareTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var compare
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new compare;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
